packages:
  - '../build-scripts'
  - '!**/dist/**'
  - '!**/.next/**'

autoInstallPeers: false

# Enforce that packages must be at least 2 days old before they're installed
# This reduces the risk of supply chain attacks from newly published packages
minimumReleaseAge: 2880
