name: Changesets
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # pin@v3.0.0
      - name: Install Nodejs
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # pin@v4.0.2
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: 'packages/messaging/pnpm-lock.yaml'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        working-directory: packages/messaging
        run: pnpm install --frozen-lockfile
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@f13b1baaa620fde937751f5d2c3572b9da32af23 # pin@v1
        with:
          version: pnpm changeset-version
          publish: pnpm changeset publish --tag alpha
          cwd: packages/messaging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}